# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8329b183a082354a267436fe26c29792ea09218ecbd7a1ad80603b0fca65c4ee3bd26d2ae73cacde9cba903e42469f144c519d3ed7be5c49b22b8d96d9fd45d

test:
  secret_key_base: 7639c714c9047a7e773d4da0f6e75fadff1c33811681ce8381eb3691d4151ff877a786b9d3f62b08ff8974ff699db10f2111edc235971e8a85060a1487f214e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
